name: soracom-console
version: '1.0.0'
summary: Soracom console Web App
description: |
    Soracom IoT platrofm console Web App.
    Let you open Soracom's web management console directly form applications menu
    
grade: stable
confinement: strict

apps:
  soracom-console:
    command: webapp-launcher --enable-back-forward https://console.soracom.io %u
    plugs:
      - browser-sandbox
      - network
      - network-bind
      - opengl
      - pulseaudio
      - screen-inhibit-control
      - unity7
      - mir

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: false
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

parts:
  webapp-container:
    after: [ubuntu-app-platformdesktop-ubuntu-app-platform,webapp-helper]
    plugin: nil
