name: soracom
version: '0.1.8'
summary: Soracom CLI and Web App
description: |
    Soracom IoT platrofm CLI and Web App.
    
grade: stable
confinement: strict

apps:
  soracom-console:
    command: webapp-launcher --enable-back-forward https://console.soracom.io %u
    plugs:
      - browser-sandbox
      - network
      - network-bind
      - opengl
      - pulseaudio
      - screen-inhibit-control
      - unity7
      - mir
  soracom:
    command: soracom

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: false
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

parts:
  webapp-container:
    after: [desktop-ubuntu-app-platform,webapp-helper]
    plugin: nil
  soracom-deb:
    source: https://github.com/soracom/soracom-cli/releases/download/v0.1.8/soracom_0.1.8_amd64.deb
    source-type: deb
    plugin: dump
